version: "3.8"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  real_chat_app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: "5432"
      DATABASE_USER: chatuser
      DATABASE_PASSWORD: chatpass
      DATABASE_NAME: chatdb
      # optional override:
      # BACKEND_HOST: 0.0.0.0
      # BACKEND_PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    restart: unless-stopped

volumes:
  pgdata:
